Update requirements.txt
Added versions for all the required libraries to ensure compatibility of the versions with render's libraries. This was done to solve this issue passlib==1.7.4
bcrypt==4.0.1, passlib is expecting is different version of bcrypt and causing this error : WARNING:passlib.handlers.bcrypt:(trapped) error reading bcrypt version
AttributeError: module 'bcrypt' has no attribute '__about__'